// flow-typed signature: 8b1e009c1f7661f549af9b142f7b4a5d
// flow-typed version: <<STUB>>/gatsby-plugin-accessibilityjs_v^1.0.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-accessibilityjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-accessibilityjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-accessibilityjs/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-accessibilityjs/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-accessibilityjs/get-options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-accessibilityjs/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-accessibilityjs/gatsby-browser'>;
}
declare module 'gatsby-plugin-accessibilityjs/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-accessibilityjs/gatsby-ssr'>;
}
declare module 'gatsby-plugin-accessibilityjs/get-options.js' {
  declare module.exports: $Exports<'gatsby-plugin-accessibilityjs/get-options'>;
}
declare module 'gatsby-plugin-accessibilityjs/index' {
  declare module.exports: $Exports<'gatsby-plugin-accessibilityjs'>;
}
declare module 'gatsby-plugin-accessibilityjs/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-accessibilityjs'>;
}
