// flow-typed signature: 1babecbdda3c92d8998accaa89763c35
// flow-typed version: <<STUB>>/gatsby-plugin-preact_v^1.0.17/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-preact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-preact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-preact/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preact/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-preact/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-preact/gatsby-browser'>;
}
declare module 'gatsby-plugin-preact/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-preact/gatsby-node'>;
}
declare module 'gatsby-plugin-preact/index' {
  declare module.exports: $Exports<'gatsby-plugin-preact'>;
}
declare module 'gatsby-plugin-preact/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-preact'>;
}
