// flow-typed signature: affd695b384b69a85dad213d2adb92c0
// flow-typed version: <<STUB>>/gatsby-plugin-postcss-sass_v^1.0.22/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-postcss-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-postcss-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-postcss-sass/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-postcss-sass/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-postcss-sass/gatsby-node'>;
}
declare module 'gatsby-plugin-postcss-sass/index' {
  declare module.exports: $Exports<'gatsby-plugin-postcss-sass'>;
}
declare module 'gatsby-plugin-postcss-sass/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-postcss-sass'>;
}
