// flow-typed signature: 888367708c12740de95db362c2cabef0
// flow-typed version: <<STUB>>/gatsby-plugin-catch-links_v^1.0.24/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-catch-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-catch-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-catch-links/catch-links' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-catch-links/gatsby-browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-catch-links/catch-links.js' {
  declare module.exports: $Exports<'gatsby-plugin-catch-links/catch-links'>;
}
declare module 'gatsby-plugin-catch-links/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-catch-links/gatsby-browser'>;
}
declare module 'gatsby-plugin-catch-links/index' {
  declare module.exports: $Exports<'gatsby-plugin-catch-links'>;
}
declare module 'gatsby-plugin-catch-links/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-catch-links'>;
}
