// flow-typed signature: 9ea1354a41214e6c91fc423a985f0c60
// flow-typed version: <<STUB>>/gatsby-plugin-sentry_v^0.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-sentry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-sentry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-sentry/gatsby-browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-sentry/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-sentry/gatsby-browser'>;
}
declare module 'gatsby-plugin-sentry/index' {
  declare module.exports: $Exports<'gatsby-plugin-sentry'>;
}
declare module 'gatsby-plugin-sentry/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-sentry'>;
}
