// flow-typed signature: 7ac19f8db5b8ad3b5c8db6138db84f27
// flow-typed version: <<STUB>>/gatsby-image_v^1.0.54/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-image/fragments' {
  declare module.exports: any;
}

declare module 'gatsby-image/index.m' {
  declare module.exports: any;
}

declare module 'gatsby-image/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-image/fragments.js' {
  declare module.exports: $Exports<'gatsby-image/fragments'>;
}
declare module 'gatsby-image/index' {
  declare module.exports: $Exports<'gatsby-image'>;
}
declare module 'gatsby-image/index.js' {
  declare module.exports: $Exports<'gatsby-image'>;
}
declare module 'gatsby-image/index.m.js' {
  declare module.exports: $Exports<'gatsby-image/index.m'>;
}
declare module 'gatsby-image/index.umd.js' {
  declare module.exports: $Exports<'gatsby-image/index.umd'>;
}
