// flow-typed signature: 6998b5a809cd1f54c9c83aa752d45958
// flow-typed version: <<STUB>>/gatsby-plugin-mailchimp_v^2.2.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-mailchimp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-mailchimp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-mailchimp/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-mailchimp/index' {
  declare module.exports: $Exports<'gatsby-plugin-mailchimp'>;
}
declare module 'gatsby-plugin-mailchimp/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-mailchimp'>;
}
declare module 'gatsby-plugin-mailchimp/src/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-mailchimp/src/index'>;
}
