// flow-typed signature: dede74b8083754161372bb8929968456
// flow-typed version: <<STUB>>/gatsby-plugin-canonical-urls_v^1.0.18/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-canonical-urls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-canonical-urls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-canonical-urls/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-canonical-urls/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-canonical-urls/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-canonical-urls/gatsby-browser'>;
}
declare module 'gatsby-plugin-canonical-urls/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-canonical-urls/gatsby-ssr'>;
}
declare module 'gatsby-plugin-canonical-urls/index' {
  declare module.exports: $Exports<'gatsby-plugin-canonical-urls'>;
}
declare module 'gatsby-plugin-canonical-urls/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-canonical-urls'>;
}
