// flow-typed signature: 607824fc345d195e4731504c3ddff180
// flow-typed version: <<STUB>>/gatsby-plugin-resolve-src_v^1.1.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-resolve-src'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-resolve-src' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-resolve-src/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-resolve-src/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-resolve-src/gatsby-node'>;
}
