// flow-typed signature: fe6479780c661a4996ad1e5e317ce9ed
// flow-typed version: <<STUB>>/make-plural_v^4.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'make-plural'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'make-plural' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'make-plural/bin/common' {
  declare module.exports: any;
}

declare module 'make-plural/es6/pluralCategories' {
  declare module.exports: any;
}

declare module 'make-plural/es6/plurals' {
  declare module.exports: any;
}

declare module 'make-plural/make-plural' {
  declare module.exports: any;
}

declare module 'make-plural/make-plural.min' {
  declare module.exports: any;
}

declare module 'make-plural/umd/pluralCategories' {
  declare module.exports: any;
}

declare module 'make-plural/umd/pluralCategories.min' {
  declare module.exports: any;
}

declare module 'make-plural/umd/plurals' {
  declare module.exports: any;
}

declare module 'make-plural/umd/plurals.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'make-plural/bin/common.js' {
  declare module.exports: $Exports<'make-plural/bin/common'>;
}
declare module 'make-plural/es6/pluralCategories.js' {
  declare module.exports: $Exports<'make-plural/es6/pluralCategories'>;
}
declare module 'make-plural/es6/plurals.js' {
  declare module.exports: $Exports<'make-plural/es6/plurals'>;
}
declare module 'make-plural/make-plural.js' {
  declare module.exports: $Exports<'make-plural/make-plural'>;
}
declare module 'make-plural/make-plural.min.js' {
  declare module.exports: $Exports<'make-plural/make-plural.min'>;
}
declare module 'make-plural/umd/pluralCategories.js' {
  declare module.exports: $Exports<'make-plural/umd/pluralCategories'>;
}
declare module 'make-plural/umd/pluralCategories.min.js' {
  declare module.exports: $Exports<'make-plural/umd/pluralCategories.min'>;
}
declare module 'make-plural/umd/plurals.js' {
  declare module.exports: $Exports<'make-plural/umd/plurals'>;
}
declare module 'make-plural/umd/plurals.min.js' {
  declare module.exports: $Exports<'make-plural/umd/plurals.min'>;
}
