// flow-typed signature: 7ed8b0acdebf4de3bd397ca63785353c
// flow-typed version: <<STUB>>/materialize-css_v^1.0.0-rc.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'materialize-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'materialize-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'materialize-css/dist/js/materialize' {
  declare module.exports: any;
}

declare module 'materialize-css/dist/js/materialize.min' {
  declare module.exports: any;
}

declare module 'materialize-css/extras/noUiSlider/nouislider' {
  declare module.exports: any;
}

declare module 'materialize-css/extras/noUiSlider/nouislider.min' {
  declare module.exports: any;
}

declare module 'materialize-css/Gruntfile' {
  declare module.exports: any;
}

declare module 'materialize-css/js/anime.min' {
  declare module.exports: any;
}

declare module 'materialize-css/js/autocomplete' {
  declare module.exports: any;
}

declare module 'materialize-css/js/buttons' {
  declare module.exports: any;
}

declare module 'materialize-css/js/cards' {
  declare module.exports: any;
}

declare module 'materialize-css/js/carousel' {
  declare module.exports: any;
}

declare module 'materialize-css/js/cash' {
  declare module.exports: any;
}

declare module 'materialize-css/js/characterCounter' {
  declare module.exports: any;
}

declare module 'materialize-css/js/chips' {
  declare module.exports: any;
}

declare module 'materialize-css/js/collapsible' {
  declare module.exports: any;
}

declare module 'materialize-css/js/component' {
  declare module.exports: any;
}

declare module 'materialize-css/js/datepicker' {
  declare module.exports: any;
}

declare module 'materialize-css/js/dropdown' {
  declare module.exports: any;
}

declare module 'materialize-css/js/forms' {
  declare module.exports: any;
}

declare module 'materialize-css/js/global' {
  declare module.exports: any;
}

declare module 'materialize-css/js/materialbox' {
  declare module.exports: any;
}

declare module 'materialize-css/js/modal' {
  declare module.exports: any;
}

declare module 'materialize-css/js/parallax' {
  declare module.exports: any;
}

declare module 'materialize-css/js/pushpin' {
  declare module.exports: any;
}

declare module 'materialize-css/js/range' {
  declare module.exports: any;
}

declare module 'materialize-css/js/scrollspy' {
  declare module.exports: any;
}

declare module 'materialize-css/js/select' {
  declare module.exports: any;
}

declare module 'materialize-css/js/sidenav' {
  declare module.exports: any;
}

declare module 'materialize-css/js/slider' {
  declare module.exports: any;
}

declare module 'materialize-css/js/tabs' {
  declare module.exports: any;
}

declare module 'materialize-css/js/tapTarget' {
  declare module.exports: any;
}

declare module 'materialize-css/js/timepicker' {
  declare module.exports: any;
}

declare module 'materialize-css/js/toasts' {
  declare module.exports: any;
}

declare module 'materialize-css/js/tooltip' {
  declare module.exports: any;
}

declare module 'materialize-css/js/waves' {
  declare module.exports: any;
}

// Filename aliases
declare module 'materialize-css/dist/js/materialize.js' {
  declare module.exports: $Exports<'materialize-css/dist/js/materialize'>;
}
declare module 'materialize-css/dist/js/materialize.min.js' {
  declare module.exports: $Exports<'materialize-css/dist/js/materialize.min'>;
}
declare module 'materialize-css/extras/noUiSlider/nouislider.js' {
  declare module.exports: $Exports<'materialize-css/extras/noUiSlider/nouislider'>;
}
declare module 'materialize-css/extras/noUiSlider/nouislider.min.js' {
  declare module.exports: $Exports<'materialize-css/extras/noUiSlider/nouislider.min'>;
}
declare module 'materialize-css/Gruntfile.js' {
  declare module.exports: $Exports<'materialize-css/Gruntfile'>;
}
declare module 'materialize-css/js/anime.min.js' {
  declare module.exports: $Exports<'materialize-css/js/anime.min'>;
}
declare module 'materialize-css/js/autocomplete.js' {
  declare module.exports: $Exports<'materialize-css/js/autocomplete'>;
}
declare module 'materialize-css/js/buttons.js' {
  declare module.exports: $Exports<'materialize-css/js/buttons'>;
}
declare module 'materialize-css/js/cards.js' {
  declare module.exports: $Exports<'materialize-css/js/cards'>;
}
declare module 'materialize-css/js/carousel.js' {
  declare module.exports: $Exports<'materialize-css/js/carousel'>;
}
declare module 'materialize-css/js/cash.js' {
  declare module.exports: $Exports<'materialize-css/js/cash'>;
}
declare module 'materialize-css/js/characterCounter.js' {
  declare module.exports: $Exports<'materialize-css/js/characterCounter'>;
}
declare module 'materialize-css/js/chips.js' {
  declare module.exports: $Exports<'materialize-css/js/chips'>;
}
declare module 'materialize-css/js/collapsible.js' {
  declare module.exports: $Exports<'materialize-css/js/collapsible'>;
}
declare module 'materialize-css/js/component.js' {
  declare module.exports: $Exports<'materialize-css/js/component'>;
}
declare module 'materialize-css/js/datepicker.js' {
  declare module.exports: $Exports<'materialize-css/js/datepicker'>;
}
declare module 'materialize-css/js/dropdown.js' {
  declare module.exports: $Exports<'materialize-css/js/dropdown'>;
}
declare module 'materialize-css/js/forms.js' {
  declare module.exports: $Exports<'materialize-css/js/forms'>;
}
declare module 'materialize-css/js/global.js' {
  declare module.exports: $Exports<'materialize-css/js/global'>;
}
declare module 'materialize-css/js/materialbox.js' {
  declare module.exports: $Exports<'materialize-css/js/materialbox'>;
}
declare module 'materialize-css/js/modal.js' {
  declare module.exports: $Exports<'materialize-css/js/modal'>;
}
declare module 'materialize-css/js/parallax.js' {
  declare module.exports: $Exports<'materialize-css/js/parallax'>;
}
declare module 'materialize-css/js/pushpin.js' {
  declare module.exports: $Exports<'materialize-css/js/pushpin'>;
}
declare module 'materialize-css/js/range.js' {
  declare module.exports: $Exports<'materialize-css/js/range'>;
}
declare module 'materialize-css/js/scrollspy.js' {
  declare module.exports: $Exports<'materialize-css/js/scrollspy'>;
}
declare module 'materialize-css/js/select.js' {
  declare module.exports: $Exports<'materialize-css/js/select'>;
}
declare module 'materialize-css/js/sidenav.js' {
  declare module.exports: $Exports<'materialize-css/js/sidenav'>;
}
declare module 'materialize-css/js/slider.js' {
  declare module.exports: $Exports<'materialize-css/js/slider'>;
}
declare module 'materialize-css/js/tabs.js' {
  declare module.exports: $Exports<'materialize-css/js/tabs'>;
}
declare module 'materialize-css/js/tapTarget.js' {
  declare module.exports: $Exports<'materialize-css/js/tapTarget'>;
}
declare module 'materialize-css/js/timepicker.js' {
  declare module.exports: $Exports<'materialize-css/js/timepicker'>;
}
declare module 'materialize-css/js/toasts.js' {
  declare module.exports: $Exports<'materialize-css/js/toasts'>;
}
declare module 'materialize-css/js/tooltip.js' {
  declare module.exports: $Exports<'materialize-css/js/tooltip'>;
}
declare module 'materialize-css/js/waves.js' {
  declare module.exports: $Exports<'materialize-css/js/waves'>;
}
