// flow-typed signature: 3a1da2fb4023a8189fd9997bd3283ab1
// flow-typed version: <<STUB>>/slash_v^2.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'slash/index' {
  declare module.exports: $Exports<'slash'>;
}
declare module 'slash/index.js' {
  declare module.exports: $Exports<'slash'>;
}
