// flow-typed signature: a3f6516ade26ec3209c1803e7e2acb4f
// flow-typed version: <<STUB>>/svg-icon_v^0.8.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-icon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-icon/bin/cli' {
  declare module.exports: any;
}

declare module 'svg-icon/bin/generate-demo-data' {
  declare module.exports: any;
}

declare module 'svg-icon/bin/sync-icons' {
  declare module.exports: any;
}

declare module 'svg-icon/bin/trim-svg-icon' {
  declare module.exports: any;
}

declare module 'svg-icon/bin/trim-svg-icons' {
  declare module.exports: any;
}

declare module 'svg-icon/dist/index' {
  declare module.exports: any;
}

declare module 'svg-icon/dist/lib/jquery-2.2.4.min' {
  declare module.exports: any;
}

declare module 'svg-icon/dist/svg-icon-element' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/alias' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/amd2commonjs' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/babel' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/cmd2commonjs' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/commonjs2es6' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/config' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/demo-data' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/dev' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/eslint' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/jsdoc' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/meta-data' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/pack' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/svg-sprite' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/svgmin' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/sync-icons' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/template2module' {
  declare module.exports: any;
}

declare module 'svg-icon/gulp/watch' {
  declare module.exports: any;
}

declare module 'svg-icon/gulpfile' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/build' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/const/icons-meta-by-name' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/const/icons-meta-by-prefix' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/const/icons-meta' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/iconize' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separate' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/ant-design' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/bootstrap' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/devicons' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/elusive-iconfont' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/entypo' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/evil-icons' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/flag-icon' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/flat-ui' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/font-awesome' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/foundation' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/game-icons' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/geomicons-open' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/icomoon-free' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/icon-font' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/index' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/ionicons' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/logos' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/maki' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/map-icons' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/material-design' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/metro-ui-css' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/mfglabs-iconset' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/octicons' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/open-iconic' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/payment-font' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/payment-webfont' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/simple-icons' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/subway' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/typicons' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/weather-icons' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/windows-icons' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/separator/zocial' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/template/collection' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/template/svg-sprite' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/clear-attrs' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/fix-id' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/generate-id' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/generate-svg-icon' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/generate-svg-sprite' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/generate-svg' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/index' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/svg2symbol' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/svgmin' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/svgo' {
  declare module.exports: any;
}

declare module 'svg-icon/lib/util/trim-svg' {
  declare module.exports: any;
}

declare module 'svg-icon/spec/index' {
  declare module.exports: any;
}

declare module 'svg-icon/spec/index.spec' {
  declare module.exports: any;
}

declare module 'svg-icon/spec/lib/iconize' {
  declare module.exports: any;
}

declare module 'svg-icon/src/index' {
  declare module.exports: any;
}

declare module 'svg-icon/src/svg-icon-element' {
  declare module.exports: any;
}

declare module 'svg-icon/webpack-dev.config' {
  declare module.exports: any;
}

declare module 'svg-icon/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-icon/bin/cli.js' {
  declare module.exports: $Exports<'svg-icon/bin/cli'>;
}
declare module 'svg-icon/bin/generate-demo-data.js' {
  declare module.exports: $Exports<'svg-icon/bin/generate-demo-data'>;
}
declare module 'svg-icon/bin/sync-icons.js' {
  declare module.exports: $Exports<'svg-icon/bin/sync-icons'>;
}
declare module 'svg-icon/bin/trim-svg-icon.js' {
  declare module.exports: $Exports<'svg-icon/bin/trim-svg-icon'>;
}
declare module 'svg-icon/bin/trim-svg-icons.js' {
  declare module.exports: $Exports<'svg-icon/bin/trim-svg-icons'>;
}
declare module 'svg-icon/dist/index.js' {
  declare module.exports: $Exports<'svg-icon/dist/index'>;
}
declare module 'svg-icon/dist/lib/jquery-2.2.4.min.js' {
  declare module.exports: $Exports<'svg-icon/dist/lib/jquery-2.2.4.min'>;
}
declare module 'svg-icon/dist/svg-icon-element.js' {
  declare module.exports: $Exports<'svg-icon/dist/svg-icon-element'>;
}
declare module 'svg-icon/gulp/alias.js' {
  declare module.exports: $Exports<'svg-icon/gulp/alias'>;
}
declare module 'svg-icon/gulp/amd2commonjs.js' {
  declare module.exports: $Exports<'svg-icon/gulp/amd2commonjs'>;
}
declare module 'svg-icon/gulp/babel.js' {
  declare module.exports: $Exports<'svg-icon/gulp/babel'>;
}
declare module 'svg-icon/gulp/cmd2commonjs.js' {
  declare module.exports: $Exports<'svg-icon/gulp/cmd2commonjs'>;
}
declare module 'svg-icon/gulp/commonjs2es6.js' {
  declare module.exports: $Exports<'svg-icon/gulp/commonjs2es6'>;
}
declare module 'svg-icon/gulp/config.js' {
  declare module.exports: $Exports<'svg-icon/gulp/config'>;
}
declare module 'svg-icon/gulp/demo-data.js' {
  declare module.exports: $Exports<'svg-icon/gulp/demo-data'>;
}
declare module 'svg-icon/gulp/dev.js' {
  declare module.exports: $Exports<'svg-icon/gulp/dev'>;
}
declare module 'svg-icon/gulp/eslint.js' {
  declare module.exports: $Exports<'svg-icon/gulp/eslint'>;
}
declare module 'svg-icon/gulp/jsdoc.js' {
  declare module.exports: $Exports<'svg-icon/gulp/jsdoc'>;
}
declare module 'svg-icon/gulp/meta-data.js' {
  declare module.exports: $Exports<'svg-icon/gulp/meta-data'>;
}
declare module 'svg-icon/gulp/pack.js' {
  declare module.exports: $Exports<'svg-icon/gulp/pack'>;
}
declare module 'svg-icon/gulp/svg-sprite.js' {
  declare module.exports: $Exports<'svg-icon/gulp/svg-sprite'>;
}
declare module 'svg-icon/gulp/svgmin.js' {
  declare module.exports: $Exports<'svg-icon/gulp/svgmin'>;
}
declare module 'svg-icon/gulp/sync-icons.js' {
  declare module.exports: $Exports<'svg-icon/gulp/sync-icons'>;
}
declare module 'svg-icon/gulp/template2module.js' {
  declare module.exports: $Exports<'svg-icon/gulp/template2module'>;
}
declare module 'svg-icon/gulp/watch.js' {
  declare module.exports: $Exports<'svg-icon/gulp/watch'>;
}
declare module 'svg-icon/gulpfile.js' {
  declare module.exports: $Exports<'svg-icon/gulpfile'>;
}
declare module 'svg-icon/index' {
  declare module.exports: $Exports<'svg-icon'>;
}
declare module 'svg-icon/index.js' {
  declare module.exports: $Exports<'svg-icon'>;
}
declare module 'svg-icon/lib/build.js' {
  declare module.exports: $Exports<'svg-icon/lib/build'>;
}
declare module 'svg-icon/lib/const/icons-meta-by-name.js' {
  declare module.exports: $Exports<'svg-icon/lib/const/icons-meta-by-name'>;
}
declare module 'svg-icon/lib/const/icons-meta-by-prefix.js' {
  declare module.exports: $Exports<'svg-icon/lib/const/icons-meta-by-prefix'>;
}
declare module 'svg-icon/lib/const/icons-meta.js' {
  declare module.exports: $Exports<'svg-icon/lib/const/icons-meta'>;
}
declare module 'svg-icon/lib/iconize.js' {
  declare module.exports: $Exports<'svg-icon/lib/iconize'>;
}
declare module 'svg-icon/lib/separate.js' {
  declare module.exports: $Exports<'svg-icon/lib/separate'>;
}
declare module 'svg-icon/lib/separator/ant-design.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/ant-design'>;
}
declare module 'svg-icon/lib/separator/bootstrap.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/bootstrap'>;
}
declare module 'svg-icon/lib/separator/devicons.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/devicons'>;
}
declare module 'svg-icon/lib/separator/elusive-iconfont.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/elusive-iconfont'>;
}
declare module 'svg-icon/lib/separator/entypo.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/entypo'>;
}
declare module 'svg-icon/lib/separator/evil-icons.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/evil-icons'>;
}
declare module 'svg-icon/lib/separator/flag-icon.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/flag-icon'>;
}
declare module 'svg-icon/lib/separator/flat-ui.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/flat-ui'>;
}
declare module 'svg-icon/lib/separator/font-awesome.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/font-awesome'>;
}
declare module 'svg-icon/lib/separator/foundation.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/foundation'>;
}
declare module 'svg-icon/lib/separator/game-icons.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/game-icons'>;
}
declare module 'svg-icon/lib/separator/geomicons-open.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/geomicons-open'>;
}
declare module 'svg-icon/lib/separator/icomoon-free.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/icomoon-free'>;
}
declare module 'svg-icon/lib/separator/icon-font.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/icon-font'>;
}
declare module 'svg-icon/lib/separator/index.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/index'>;
}
declare module 'svg-icon/lib/separator/ionicons.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/ionicons'>;
}
declare module 'svg-icon/lib/separator/logos.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/logos'>;
}
declare module 'svg-icon/lib/separator/maki.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/maki'>;
}
declare module 'svg-icon/lib/separator/map-icons.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/map-icons'>;
}
declare module 'svg-icon/lib/separator/material-design.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/material-design'>;
}
declare module 'svg-icon/lib/separator/metro-ui-css.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/metro-ui-css'>;
}
declare module 'svg-icon/lib/separator/mfglabs-iconset.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/mfglabs-iconset'>;
}
declare module 'svg-icon/lib/separator/octicons.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/octicons'>;
}
declare module 'svg-icon/lib/separator/open-iconic.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/open-iconic'>;
}
declare module 'svg-icon/lib/separator/payment-font.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/payment-font'>;
}
declare module 'svg-icon/lib/separator/payment-webfont.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/payment-webfont'>;
}
declare module 'svg-icon/lib/separator/simple-icons.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/simple-icons'>;
}
declare module 'svg-icon/lib/separator/subway.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/subway'>;
}
declare module 'svg-icon/lib/separator/typicons.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/typicons'>;
}
declare module 'svg-icon/lib/separator/weather-icons.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/weather-icons'>;
}
declare module 'svg-icon/lib/separator/windows-icons.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/windows-icons'>;
}
declare module 'svg-icon/lib/separator/zocial.js' {
  declare module.exports: $Exports<'svg-icon/lib/separator/zocial'>;
}
declare module 'svg-icon/lib/template/collection.js' {
  declare module.exports: $Exports<'svg-icon/lib/template/collection'>;
}
declare module 'svg-icon/lib/template/svg-sprite.js' {
  declare module.exports: $Exports<'svg-icon/lib/template/svg-sprite'>;
}
declare module 'svg-icon/lib/util/clear-attrs.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/clear-attrs'>;
}
declare module 'svg-icon/lib/util/fix-id.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/fix-id'>;
}
declare module 'svg-icon/lib/util/generate-id.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/generate-id'>;
}
declare module 'svg-icon/lib/util/generate-svg-icon.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/generate-svg-icon'>;
}
declare module 'svg-icon/lib/util/generate-svg-sprite.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/generate-svg-sprite'>;
}
declare module 'svg-icon/lib/util/generate-svg.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/generate-svg'>;
}
declare module 'svg-icon/lib/util/index.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/index'>;
}
declare module 'svg-icon/lib/util/svg2symbol.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/svg2symbol'>;
}
declare module 'svg-icon/lib/util/svgmin.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/svgmin'>;
}
declare module 'svg-icon/lib/util/svgo.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/svgo'>;
}
declare module 'svg-icon/lib/util/trim-svg.js' {
  declare module.exports: $Exports<'svg-icon/lib/util/trim-svg'>;
}
declare module 'svg-icon/spec/index.js' {
  declare module.exports: $Exports<'svg-icon/spec/index'>;
}
declare module 'svg-icon/spec/index.spec.js' {
  declare module.exports: $Exports<'svg-icon/spec/index.spec'>;
}
declare module 'svg-icon/spec/lib/iconize.js' {
  declare module.exports: $Exports<'svg-icon/spec/lib/iconize'>;
}
declare module 'svg-icon/src/index.js' {
  declare module.exports: $Exports<'svg-icon/src/index'>;
}
declare module 'svg-icon/src/svg-icon-element.js' {
  declare module.exports: $Exports<'svg-icon/src/svg-icon-element'>;
}
declare module 'svg-icon/webpack-dev.config.js' {
  declare module.exports: $Exports<'svg-icon/webpack-dev.config'>;
}
declare module 'svg-icon/webpack.config.js' {
  declare module.exports: $Exports<'svg-icon/webpack.config'>;
}
