// flow-typed signature: 7cad54347e2f47ed59284e9059bf4815
// flow-typed version: <<STUB>>/tachyons_v^4.9.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons' {
  declare module.exports: any;
}
