// flow-typed signature: 65bb9c90449135e19e7045c50f5e2346
// flow-typed version: <<STUB>>/typeface-amiri_v^0.0.56/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-amiri'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-amiri' {
  declare module.exports: any;
}
