// flow-typed signature: 254d62d0a2613270ba8e20cd2a8f158c
// flow-typed version: <<STUB>>/typeface-open-sans_v^0.0.54/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-open-sans'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-open-sans' {
  declare module.exports: any;
}
