// flow-typed signature: 20f6126e2fb55907cb2e77ed203ce8f2
// flow-typed version: <<STUB>>/@material/button_v^0.35.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/button' {
  declare module.exports: any;
}
