// flow-typed signature: ccd95659a5719ada06b73f37902d76ce
// flow-typed version: <<STUB>>/@material/card_v^0.35.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/card'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/card' {
  declare module.exports: any;
}
