// flow-typed signature: 1ea0c69b0a85b731206c385cd471b10c
// flow-typed version: <<STUB>>/@material/linear-progress_v^0.35.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/linear-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/linear-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/linear-progress/constants' {
  declare module.exports: any;
}

declare module '@material/linear-progress/dist/mdc.linearProgress' {
  declare module.exports: any;
}

declare module '@material/linear-progress/dist/mdc.linearProgress.min' {
  declare module.exports: any;
}

declare module '@material/linear-progress/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/linear-progress/constants.js' {
  declare module.exports: $Exports<'@material/linear-progress/constants'>;
}
declare module '@material/linear-progress/dist/mdc.linearProgress.js' {
  declare module.exports: $Exports<'@material/linear-progress/dist/mdc.linearProgress'>;
}
declare module '@material/linear-progress/dist/mdc.linearProgress.min.js' {
  declare module.exports: $Exports<'@material/linear-progress/dist/mdc.linearProgress.min'>;
}
declare module '@material/linear-progress/foundation.js' {
  declare module.exports: $Exports<'@material/linear-progress/foundation'>;
}
declare module '@material/linear-progress/index' {
  declare module.exports: $Exports<'@material/linear-progress'>;
}
declare module '@material/linear-progress/index.js' {
  declare module.exports: $Exports<'@material/linear-progress'>;
}
