// flow-typed signature: cee91d68cf154089845f72851b757452
// flow-typed version: <<STUB>>/@material/textfield_v^0.35.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/textfield'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/textfield' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/textfield/adapter' {
  declare module.exports: any;
}

declare module '@material/textfield/constants' {
  declare module.exports: any;
}

declare module '@material/textfield/dist/mdc.textfield' {
  declare module.exports: any;
}

declare module '@material/textfield/dist/mdc.textfield.min' {
  declare module.exports: any;
}

declare module '@material/textfield/foundation' {
  declare module.exports: any;
}

declare module '@material/textfield/helper-text/adapter' {
  declare module.exports: any;
}

declare module '@material/textfield/helper-text/constants' {
  declare module.exports: any;
}

declare module '@material/textfield/helper-text/foundation' {
  declare module.exports: any;
}

declare module '@material/textfield/helper-text/index' {
  declare module.exports: any;
}

declare module '@material/textfield/icon/adapter' {
  declare module.exports: any;
}

declare module '@material/textfield/icon/constants' {
  declare module.exports: any;
}

declare module '@material/textfield/icon/foundation' {
  declare module.exports: any;
}

declare module '@material/textfield/icon/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/textfield/adapter.js' {
  declare module.exports: $Exports<'@material/textfield/adapter'>;
}
declare module '@material/textfield/constants.js' {
  declare module.exports: $Exports<'@material/textfield/constants'>;
}
declare module '@material/textfield/dist/mdc.textfield.js' {
  declare module.exports: $Exports<'@material/textfield/dist/mdc.textfield'>;
}
declare module '@material/textfield/dist/mdc.textfield.min.js' {
  declare module.exports: $Exports<'@material/textfield/dist/mdc.textfield.min'>;
}
declare module '@material/textfield/foundation.js' {
  declare module.exports: $Exports<'@material/textfield/foundation'>;
}
declare module '@material/textfield/helper-text/adapter.js' {
  declare module.exports: $Exports<'@material/textfield/helper-text/adapter'>;
}
declare module '@material/textfield/helper-text/constants.js' {
  declare module.exports: $Exports<'@material/textfield/helper-text/constants'>;
}
declare module '@material/textfield/helper-text/foundation.js' {
  declare module.exports: $Exports<'@material/textfield/helper-text/foundation'>;
}
declare module '@material/textfield/helper-text/index.js' {
  declare module.exports: $Exports<'@material/textfield/helper-text/index'>;
}
declare module '@material/textfield/icon/adapter.js' {
  declare module.exports: $Exports<'@material/textfield/icon/adapter'>;
}
declare module '@material/textfield/icon/constants.js' {
  declare module.exports: $Exports<'@material/textfield/icon/constants'>;
}
declare module '@material/textfield/icon/foundation.js' {
  declare module.exports: $Exports<'@material/textfield/icon/foundation'>;
}
declare module '@material/textfield/icon/index.js' {
  declare module.exports: $Exports<'@material/textfield/icon/index'>;
}
declare module '@material/textfield/index' {
  declare module.exports: $Exports<'@material/textfield'>;
}
declare module '@material/textfield/index.js' {
  declare module.exports: $Exports<'@material/textfield'>;
}
