// flow-typed signature: 33cc8bc868631cde854d991741607440
// flow-typed version: <<STUB>>/@material/theme_v^0.35.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/theme' {
  declare module.exports: any;
}
