// flow-typed signature: b926fdeb69fb24f4844e89cd4c23b928
// flow-typed version: <<STUB>>/@material/theme_v^0.35.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/theme' {
  declare module.exports: any;
}
