// flow-typed signature: f9beda586460e22a060ce55bd5994ea2
// flow-typed version: <<STUB>>/@material/typography_v^0.35.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/typography' {
  declare module.exports: any;
}
